# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!
# ---------------
# theme_color:
#   enable: true
#   main: "#49B1F5"
#   paginator: "#00C4B6"
#   button_hover: "#FF7242"
#   text_selection: "#00C4B6"
#   link_color: "#858585"
#   hr_color: "#A4D8FA"

# Main menu navigation
# ---------------
menu:
  首页: /
  档案: /archives
  标签: /tags
  类别: /categories
  #XXX: /xxx

# Favicon
# use my-favicon.ico to avoid duplicate favicon of melody theme
# ---------------
favicon: /favicon.ico

# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
pwa:
  enable: false
  manifest: /manifest.json
  # If you don't want to trouble, just ignore the following things
  # See https://realfavicongenerator.net/
  # theme_color: "#1B9EF3"
  # apple_touch_icon: /apple-touch-icon.png
  # favicon_32_32: /favicon-32x32.png
  # favicon_16_16: /favicon-16x16.png
  # mask_icon: /safari-pinned-tab.svg


# Highlight theme
# ---------------
highlight_theme: light

code_word_wrap: true

# Nav settings
# ---------------
social:
  github fa: https://github.com/roMummy
  rss fa: /atom.xml
# Algolia search
# ---------------
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # if there are no result
    hits_stats: "${hits} results found in ${time} ms"


# Local search
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/third-party-support?id=local-search
# ---------------
local_search:
  enable: true
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # if there are no result

# MathJax
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/third-party-support?id=mathjax
# ---------------
mathjax:
  enable: false
  cdn: https://cdn.jsdelivr.net/npm/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML


# Toggle fireworks (IE >= 10)
# ---------------
fireworks: false

# Analysis
# ---------------
baidu_analytics:

google_analytics:

# stylesheets loaded in the <head>
# ---------------
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
# ---------------
scripts:
- /js/utils.js
- /js/fancybox.js
- /js/sidebar.js
- /js/copy.js
- /js/fireworks.js
- /js/transition.js
- /js/scroll.js
- /js/head.js

# cdn for third-party library
# ---------------
cdn:
  css:
    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
#    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css
#    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font/css/font-awesome.min.css
#    fontawesomev5: https://use.fontawesome.com/releases/v5.7.2/css/all.css
  js:
    anime: /js/third-party/anime.min.js
    jquery: /js/third-party/jquery.min.js
    fancybox: /js/third-party/jquery.fancybox.min.js
    velocity: /js/third-party/velocity.min.js
    velocity-ui: /js/third-party/velocity.ui.min.js

# Post info settings
# ---------------
avatar: https://ss0.bdstatic.com/94oJfD_bAAcT8t7mm9GUKT-xh_/timg?image&quality=100&size=b4000_4000&sec=1530072864&di=b83735a6b8cfd2147078a2bbf06d7570&src=http://ww2.sinaimg.cn/wap720/63a4b031jw1f4lxxamw0jj218g0qodib.jpg

top_img: https://blog-1251750343.cos.ap-beijing.myqcloud.com/blog/blog-bg.jpg
#- /img/top.jpg # false or url of img

post_meta:
  date_type: created # created or updated
  categories: true
  tags: true

# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/additional-package-support?id=word-counting
wordcount:
  enable: true

toc:
  enable: true
  # number: true

post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/#/theme-config?id=auto-excerpt
auto_excerpt:
  enable: true
  length: 150

# slide
# For reveal.js config, see https://github.com/hakimel/reveal.js#configuration
slide:
  separator: ---
  separator_vertical: --
  charset: utf-8
  theme: black
  # optional
  mouseWheel: false
  transition: slide
  transitionSpeed: default
  parallaxBackgroundImage: ''
  parallaxBackgroundSize: ''
  parallaxBackgroundHorizontal: null
  parallaxBackgroundVertical: null

# QR_code:
  # - itemlist:
  #     img:
  #     text:

# adv:
  # enable: false
  # info:

# Share System
# ---------------
addThis:
  enable: false
  #pubid:

sharejs:
  enable: true
  sites: qzone,qq,weibo,wechat,google,facebook,twitter

# Comments System
# ---------------
disqus:
  enable: false
#   shortname: disqus_fBWm0RrawQ
#   count: true

# laibili:
  # enable: false
  # uid:

# gitment
  # enable: false
  # owner:
  # repo:
  # client_id:
  # client_secret:

gitalk:
  enable: true
  client_id: 24af658de34aaa18ccee
  client_secret: 91cd56ec2ab784fc8436eec4ee72d7a7dde9e158
  repo: romummy.github.io
  owner: roMummy
  admin: roMummy
####   Using this js for redirect to gitalk container after login
####   See https://github.com/gitalk/gitalk/issues/125
#   js: https://cdn.jsdelivr.net/gh/upupming/gitalk@36368e5dffd049e956cdbbd751ff96c28d8255cf/dist/gitalk.min.js

# valine comment system. https://valine.js.org
# valine:
#   enable: false # if you want use valine,please set this value is ture
#   appId:  # leancloud application app id
#   appKey:  # leancloud application app key
#   notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
#   verify: false # valine verify code (true/false)
#   pageSize: 10 # comment list page size
#   avatar: mm # gravatar style https://valine.js.org/#/avatar
#   lang: zh-cn # i18n: zh-cn/en
#   placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
#   guest_info: nick,mail,link #valine comment header inf

# Footer Settings
# ---------------
since: 2013

# footer_custom_text:

ICP:
  enable: false
  #text:

# busuanzi count for PV / UV in site
busuanzi:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file-o"></i>
  page_pv_footer:


# Sidebar Settings
# ---------------
links_title: Links
links:
  me: https://github.com/roMummy

# Follow Me Button
follow:
  enable: true
  url: 'https://github.com/roMummy'
  text: 'github'
